version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9  # Use an image with both azcopy and aws-cli pre-installed, or install them in the next steps
    working_directory: ~/repo
jobs:
  backup:
    docker:
      - image: circleci/python:3.9  # You can replace this with an image that already has AWS CLI and Azure CLI
    steps:
      - checkout
      - run:
          name: Install Azure CLI and AWS CLI
          command: |
            # Install Azure CLI
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            # Install AWS CLI
            sudo apt-get install -y awscli
            # Install AzCopy
            wget https://aka.ms/downloadazcopy-v10-linux -O azcopy.tar.gz
            tar -xvzf azcopy.tar.gz
            sudo mv azcopy*/azcopy /usr/bin/
            az --version
            aws --version
      - run:
          name: Set up Azure Authentication
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - run:
          name: Set up AWS Authentication with Session Token
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set aws_session_token $AWS_SESSION_TOKEN
            aws configure set region $AWS_REGION
      - run:
          name: Run Backup Script
          command: |
            chmod +x ./backup_script.sh
            ./backup_script.sh
      - run:
          name: Clean up
          command: |
            # Add any additional cleanup steps if needed
workflows:
  version: 2
  backup_process:
    jobs:
      - backup
